#!/usr/bin/env bash

ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc

ln -s $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
ln -s $HOME/.dotfiles/.gitignore $HOME/.gitignore
ln -s $HOME/.dotfiles/.gitattributes $HOME/.gitattributes
