#!/usr/bin/env bash

# Install homebrew
$(which bash) -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed
# Install a modern version of ZSH.
brew install zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting romkatv/powerlevel10k/powerlevel10k

# Switch to using brew-installed zsh as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/zsh" /etc/shells; then
  echo "${BREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells;
  chsh -s "${BREW_PREFIX}/bin/zsh";
fi;

# Install `wget` with IRI support.
brew install wget

# Install GnuPG to enable PGP-signing commits.
brew install gnupg

# Install more recent versions of some macOS tools.
brew install vim
brew install grep
brew install openssh
brew install screen
brew install php
brew install gmp

# Install casks
brew install --cask alfred
brew install --cask imageoptim
brew install --cask firefox
brew install --cask microsoft-edge
brew install --cask google-chrome
brew install --cask brave-browser
brew install --cask visual-studio-code
brew install --cask iterm2
brew install --cask gpg-suite-no-mail

# Configure iterm
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.dotfiles/setup"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Install other useful tools
brew install git
brew install git-lfs
brew install ssh-copy-id

# Install pass
brew tap amar1729/formulae
brew install pass browserpass

PREFIX='/opt/homebrew/opt/browserpass' make hosts-chrome-user -f /opt/homebrew/opt/browserpass/lib/browserpass/Makefile
PREFIX='/opt/homebrew/opt/browserpass' make hosts-brave-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'

# Configure GPG as SSH agent
echo "enable-ssh-support" >> $HOME/.gnupg/gpg-agent.conf

# Install wol
source $HOME/.dotfiles/.exports

brew install go
go install github.com/crossi36/wol@latest

# Install tailscale
brew install --cask tailscale

# Remove outdated versions from the cellar.
brew cleanup
