#!/usr/bin/env bash

# Install homebrew
$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names
# Install a modern version of ZSH.
brew install zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting romkatv/powerlevel10k/powerlevel10k

# Switch to using brew-installed zsh as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/zsh" /etc/shells; then
  echo "${BREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells;
  chsh -s "${BREW_PREFIX}/bin/zsh";
fi;

# Install `wget` with IRI support.
brew install wget --with-iri

# Install GnuPG to enable PGP-signing commits.
brew install gnupg

# Install more recent versions of some macOS tools.
brew install vim --with-override-system-vi
brew install grep
brew install openssh
brew install screen
brew install php
brew install gmp

# Install casks
brew cask install alfred
brew cask install imageoptim
brew cask install firefox
brew cask install microsoft-edge
brew cask install iterm2
brew cask install google-chrome google-chrome-canary

# Install other useful tools
brew install git
brew install git-lfs
brew install ssh-copy-id
brew install pass browserpass

# Configure browserpass
cd $(brew --prefix)/lib/browserpass
make hosts-chrome-user

# Remove outdated versions from the cellar.
brew cleanup
